server:
  port: 8083

spring:
  kafka:
    consumer:
      group-id: fraud-detector
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092
management:
  endpoints:
    web:
      exposure:
        include: "*"
